/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bas/{quarter}/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get BAS summary for a quarter
         * @description Calculates G1 (total sales), 1A (GST collected), 1B (GST paid) for Australian BAS reporting.
         */
        get: operations["BasController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bas/quarters/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all quarter date ranges for a financial year
         * @description Returns start and end dates for all four quarters of an Australian financial year.
         */
        get: operations["BasController_getQuarters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["CategoriesController_findAll"];
        put?: never;
        /** Create a new category */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category by ID */
        get: operations["CategoriesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a category */
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        /** Update a category */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all clients */
        get: operations["ClientsController_findAll"];
        put?: never;
        /** Create a new client */
        post: operations["ClientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a client by ID */
        get: operations["ClientsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a client */
        delete: operations["ClientsController_remove"];
        options?: never;
        head?: never;
        /** Update a client */
        patch: operations["ClientsController_update"];
        trace?: never;
    };
    "/import/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import expenses from CSV
         * @description Upload a CSV file to import expenses in bulk.
         *
         *     **Supported Formats:**
         *     - Custom format with configurable column mapping
         *     - CommBank export format
         *     - Amex export format
         *
         *     **Column Requirements:**
         *     - Date: Transaction date (YYYY-MM-DD or DD/MM/YYYY)
         *     - Item: Vendor/Provider name for matching
         *     - Total: Amount including GST ($1,234.56 format)
         *     - GST (optional): GST component
         *     - Biz% (optional): Business use percentage (default 100)
         *     - Category (optional): Category name for matching
         *
         *     **Provider Matching:**
         *     Vendors are fuzzy-matched against existing providers in the database.
         *     Set a custom threshold (0-1) to adjust matching sensitivity.
         *
         *     **Duplicate Detection:**
         *     Expenses with same date, amount, and provider are considered duplicates.
         */
        post: operations["CsvImportController_importFromFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/expenses/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import expenses from CSV content
         * @description Import expenses by providing CSV content as a string in the request body.
         */
        post: operations["CsvImportController_importFromContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/expenses/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview CSV import
         * @description Validate and preview CSV import without creating expenses.
         */
        post: operations["CsvImportController_previewImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/incomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import incomes from CSV
         * @description Upload a CSV file to import incomes in bulk.
         *
         *     **Expected Format:**
         *     - Client: Client name for matching (must exist in database)
         *     - Invoice #: Invoice number (optional, used for duplicate detection)
         *     - Subtotal: Amount before GST
         *     - GST: GST collected
         *     - Total: Total amount (validated against Subtotal + GST)
         *
         *     **Client Matching:**
         *     Clients are fuzzy-matched against existing clients in the database.
         *     Since client names are encrypted, matching happens in-memory after decryption.
         *     If a client is not found, the row will fail.
         *
         *     **Total Validation:**
         *     If Total ≠ Subtotal + GST, a warning is returned and the calculated value is used.
         *
         *     **Duplicate Detection:**
         *     Incomes with same invoice number OR same date+amount+client are considered duplicates.
         */
        post: operations["CsvImportController_importIncomesFromFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/incomes/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import incomes from CSV content
         * @description Import incomes by providing CSV content as a string in the request body.
         */
        post: operations["CsvImportController_importIncomesFromContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/incomes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview income CSV import
         * @description Validate and preview CSV import without creating incomes.
         */
        post: operations["CsvImportController_previewIncomeImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all expenses with optional filtering */
        get: operations["ExpensesController_findAll"];
        put?: never;
        /**
         * Create a new expense
         * @description Creates an expense with automatic GST handling. International providers get GST=0, domestic auto-calculate GST if not provided. Response includes computed FY/Quarter fields.
         */
        post: operations["ExpensesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an expense by ID */
        get: operations["ExpensesController_findOne"];
        put?: never;
        post?: never;
        /** Delete an expense */
        delete: operations["ExpensesController_remove"];
        options?: never;
        head?: never;
        /** Update an expense */
        patch: operations["ExpensesController_update"];
        trace?: never;
    };
    "/import-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all import jobs with pagination */
        get: operations["ImportJobsController_findAll"];
        put?: never;
        /** Create a new import job */
        post: operations["ImportJobsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single import job by ID */
        get: operations["ImportJobsController_findOne"];
        put?: never;
        post?: never;
        /**
         * Delete an import job
         * @description Only allowed if the import job has no associated expenses
         */
        delete: operations["ImportJobsController_remove"];
        options?: never;
        head?: never;
        /** Update an import job */
        patch: operations["ImportJobsController_update"];
        trace?: never;
    };
    "/import-jobs/{id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get import job with its associated expenses */
        get: operations["ImportJobsController_findOneWithExpenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-jobs/{id}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get statistics for an import job */
        get: operations["ImportJobsController_getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-jobs/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback an import job
         * @description Deletes all expenses associated with this import job (hard delete)
         */
        post: operations["ImportJobsController_rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all incomes with optional filtering */
        get: operations["IncomesController_findAll"];
        put?: never;
        /**
         * Create a new income
         * @description Creates an income with automatic total calculation (subtotal + GST).
         */
        post: operations["IncomesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incomes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an income by ID */
        get: operations["IncomesController_findOne"];
        put?: never;
        post?: never;
        /** Delete an income */
        delete: operations["IncomesController_remove"];
        options?: never;
        head?: never;
        /**
         * Update an income
         * @description Updates an income. Total is recalculated if subtotal or GST changes.
         */
        patch: operations["IncomesController_update"];
        trace?: never;
    };
    "/incomes/{id}/paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark income as paid */
        patch: operations["IncomesController_markAsPaid"];
        trace?: never;
    };
    "/incomes/{id}/unpaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark income as unpaid */
        patch: operations["IncomesController_markAsUnpaid"];
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all providers */
        get: operations["ProvidersController_findAll"];
        put?: never;
        /** Create a new provider */
        post: operations["ProvidersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a provider by ID */
        get: operations["ProvidersController_findOne"];
        put?: never;
        post?: never;
        /** Delete a provider */
        delete: operations["ProvidersController_remove"];
        options?: never;
        head?: never;
        /** Update a provider */
        patch: operations["ProvidersController_update"];
        trace?: never;
    };
    "/recurring-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all recurring expense templates */
        get: operations["RecurringExpensesController_findAll"];
        put?: never;
        /** Create recurring expense template */
        post: operations["RecurringExpensesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-expenses/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recurring expenses due for generation */
        get: operations["RecurringExpensesController_findDue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-expenses/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate expenses from due templates */
        post: operations["RecurringExpensesController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recurring expense template by ID */
        get: operations["RecurringExpensesController_findOne"];
        put?: never;
        post?: never;
        /** Delete recurring expense template */
        delete: operations["RecurringExpensesController_remove"];
        options?: never;
        head?: never;
        /** Update recurring expense template */
        patch: operations["RecurringExpensesController_update"];
        trace?: never;
    };
    "/reports/fy/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get FY summary
         * @description Returns a complete financial year summary including income, expenses by category, and GST position. Useful for tax return preparation.
         */
        get: operations["ReportsController_getFYSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/fy/{year}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download FY summary as PDF
         * @description Generates a downloadable PDF report of the financial year summary. Useful for tax records and accountant submissions.
         */
        get: operations["ReportsController_getFYSummaryPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/bas/{quarter}/{year}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download BAS summary as PDF
         * @description Generates a downloadable PDF report of the BAS quarterly summary. Useful for ATO submission records.
         */
        get: operations["ReportsController_getBasSummaryPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BasSummaryDto: {
            /**
             * @description Quarter
             * @example Q1
             */
            quarter: string;
            /**
             * @description Financial year
             * @example 2025
             */
            financialYear: number;
            /**
             * @description Period start date
             * @example 2024-07-01
             */
            periodStart: string;
            /**
             * @description Period end date
             * @example 2024-09-30
             */
            periodEnd: string;
            /**
             * @description G1: Total sales in cents (inc GST)
             * @example 1100000
             */
            g1TotalSalesCents: number;
            /**
             * @description 1A: GST collected in cents
             * @example 100000
             */
            label1aGstCollectedCents: number;
            /**
             * @description 1B: GST paid in cents (claimable)
             * @example 50000
             */
            label1bGstPaidCents: number;
            /**
             * @description Net GST payable in cents (negative = refund)
             * @example 50000
             */
            netGstPayableCents: number;
            /**
             * @description Income record count
             * @example 5
             */
            incomeCount: number;
            /**
             * @description Expense record count
             * @example 12
             */
            expenseCount: number;
        };
        CreateCategoryDto: {
            /**
             * @description Category name
             * @example Software
             */
            name: string;
            /**
             * @description ATO BAS label (e.g., 1B, G10)
             * @example 1B
             */
            basLabel: string;
            /**
             * @description Tax deductible flag
             * @default true
             */
            isDeductible: boolean;
            /** @description Category description */
            description?: string;
        };
        Category: Record<string, never>;
        UpdateCategoryDto: Record<string, never>;
        CreateClientDto: {
            /**
             * @description Client legal name (encrypted at rest)
             * @example Acme Corporation Pty Ltd
             */
            name: string;
            /**
             * @description ABN - 11 digits (encrypted at rest)
             * @example 51824753556
             */
            abn?: string;
            /**
             * @description PSI eligible (affects deduction rules)
             * @default false
             */
            isPsiEligible: boolean;
        };
        Client: Record<string, never>;
        UpdateClientDto: Record<string, never>;
        CsvRowResultDto: {
            /**
             * @description Row number in CSV (1-based)
             * @example 1
             */
            rowNumber: number;
            /** @description Whether row was processed successfully */
            success: boolean;
            /** @description Whether row was skipped as duplicate */
            isDuplicate?: boolean;
            /** @description Error message if failed */
            error?: string;
            /** @description Matched provider name */
            providerName?: string;
            /** @description Provider match confidence score */
            matchScore?: number;
            /** @description Matched category name */
            categoryName?: string;
            /** @description Amount in cents */
            amountCents?: number;
            /** @description GST in cents */
            gstCents?: number;
        };
        CsvImportResponseDto: {
            /**
             * @description Import job ID for tracking
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            importJobId: string;
            /**
             * @description Total rows in CSV
             * @example 10
             */
            totalRows: number;
            /**
             * @description Successfully imported rows
             * @example 8
             */
            successCount: number;
            /**
             * @description Failed rows
             * @example 1
             */
            failedCount: number;
            /**
             * @description Duplicate rows skipped
             * @example 1
             */
            duplicateCount: number;
            /**
             * @description Total amount in cents
             * @example 125000
             */
            totalAmountCents: number;
            /**
             * @description Total GST in cents
             * @example 11363
             */
            totalGstCents: number;
            /**
             * @description Processing time in milliseconds
             * @example 150
             */
            processingTimeMs: number;
            /** @description Detailed results for each row */
            rows: components["schemas"]["CsvRowResultDto"][];
        };
        ColumnMappingDto: {
            /**
             * @description Column name for date
             * @example Date
             */
            date: string;
            /**
             * @description Column name for item/vendor
             * @example Item
             */
            item: string;
            /**
             * @description Column name for total amount
             * @example Total
             */
            total: string;
            /**
             * @description Column name for GST
             * @example GST
             */
            gst?: string;
            /**
             * @description Column name for business use %
             * @example Biz%
             */
            bizPercent?: string;
            /**
             * @description Column name for category
             * @example Category
             */
            category?: string;
            /**
             * @description Column name for description
             * @example Notes
             */
            description?: string;
        };
        CsvImportRequestDto: {
            /**
             * @description Predefined source format
             * @example custom
             * @enum {string}
             */
            source?: "custom" | "commbank" | "amex" | "nab" | "westpac" | "anz";
            /** @description Custom column mapping (overrides source) */
            mapping?: components["schemas"]["ColumnMappingDto"];
            /**
             * @description Provider matching threshold (0-1)
             * @default 0.6
             * @example 0.6
             */
            matchThreshold: number;
            /**
             * @description Skip duplicate expenses
             * @default true
             */
            skipDuplicates: boolean;
            /**
             * @description Preview mode - do not create expenses
             * @default false
             */
            dryRun: boolean;
        };
        IncomeCsvRowResultDto: {
            /**
             * @description Row number in CSV (1-based)
             * @example 1
             */
            rowNumber: number;
            /** @description Whether row was processed successfully */
            success: boolean;
            /** @description Whether row was skipped as duplicate */
            isDuplicate?: boolean;
            /** @description Error message if failed */
            error?: string;
            /** @description Warning message (e.g., total mismatch) */
            warning?: string;
            /** @description Matched client name */
            clientName?: string;
            /** @description Client match confidence score */
            matchScore?: number;
            /** @description Invoice number */
            invoiceNum?: string;
            /** @description Subtotal in cents */
            subtotalCents?: number;
            /** @description GST in cents */
            gstCents?: number;
            /** @description Total in cents */
            totalCents?: number;
        };
        IncomeCsvImportResponseDto: {
            /**
             * @description Import job ID for tracking
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            importJobId: string;
            /**
             * @description Total rows in CSV
             * @example 10
             */
            totalRows: number;
            /**
             * @description Successfully imported rows
             * @example 8
             */
            successCount: number;
            /**
             * @description Failed rows
             * @example 1
             */
            failedCount: number;
            /**
             * @description Duplicate rows skipped
             * @example 1
             */
            duplicateCount: number;
            /**
             * @description Rows with warnings
             * @example 1
             */
            warningCount: number;
            /**
             * @description Total subtotal in cents
             * @example 100000
             */
            totalSubtotalCents: number;
            /**
             * @description Total GST collected in cents
             * @example 10000
             */
            totalGstCents: number;
            /**
             * @description Total amount in cents
             * @example 110000
             */
            totalAmountCents: number;
            /**
             * @description Processing time in milliseconds
             * @example 150
             */
            processingTimeMs: number;
            /** @description Detailed results for each row */
            rows: components["schemas"]["IncomeCsvRowResultDto"][];
        };
        IncomeColumnMappingDto: {
            /**
             * @description Column name for client
             * @example Client
             */
            client: string;
            /**
             * @description Column name for invoice number
             * @example Invoice #
             */
            invoiceNum?: string;
            /**
             * @description Column name for subtotal
             * @example Subtotal
             */
            subtotal: string;
            /**
             * @description Column name for GST
             * @example GST
             */
            gst: string;
            /**
             * @description Column name for total
             * @example Total
             */
            total: string;
            /**
             * @description Column name for date
             * @example Date
             */
            date?: string;
            /**
             * @description Column name for description
             * @example Description
             */
            description?: string;
        };
        IncomeCsvImportRequestDto: {
            /**
             * @description Predefined source format
             * @example custom
             * @enum {string}
             */
            source?: "custom";
            /** @description Custom column mapping (overrides source) */
            mapping?: components["schemas"]["IncomeColumnMappingDto"];
            /**
             * @description Client matching threshold (0-1)
             * @default 0.6
             * @example 0.6
             */
            matchThreshold: number;
            /**
             * @description Skip duplicate incomes
             * @default true
             */
            skipDuplicates: boolean;
            /**
             * @description Preview mode - do not create incomes
             * @default false
             */
            dryRun: boolean;
            /**
             * @description Mark all imported incomes as paid
             * @default false
             */
            markAsPaid: boolean;
        };
        CreateExpenseDto: {
            /**
             * @description Transaction date (YYYY-MM-DD)
             * @example 2024-01-15
             */
            date: string;
            /**
             * @description Amount in cents (inc GST)
             * @example 11000
             */
            amountCents: number;
            /**
             * @description GST in cents (auto-calculated if omitted)
             * @example 1000
             */
            gstCents?: number;
            /**
             * @description Business use percentage
             * @default 100
             * @example 100
             */
            bizPercent: number;
            /**
             * @description Provider UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            providerId: string;
            /**
             * @description Category UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            categoryId: string;
            /**
             * @description Description (encrypted at rest)
             * @example GitHub Copilot subscription
             */
            description?: string;
            /**
             * @description Receipt file reference
             * @example receipt-github-2024-01.pdf
             */
            fileRef?: string;
        };
        ExpenseResponseDto: {
            /**
             * @description Expense UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * Format: date-time
             * @description Transaction date
             * @example 2025-08-15
             */
            date: string;
            /**
             * @description Description (decrypted)
             * @example GitHub Copilot subscription
             */
            description?: Record<string, never>;
            /**
             * @description Amount in cents (inc GST)
             * @example 11000
             */
            amountCents: number;
            /**
             * @description GST in cents
             * @example 1000
             */
            gstCents: number;
            /**
             * @description Business use percentage
             * @example 100
             */
            bizPercent: number;
            /**
             * @description Currency code
             * @example AUD
             */
            currency: string;
            /**
             * @description Receipt file reference
             * @example receipt-github-2024-01.pdf
             */
            fileRef?: Record<string, never>;
            /**
             * @description Provider UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            providerId: string;
            /**
             * @description Category UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            categoryId: string;
            /**
             * @description Import job UUID (null if manually created)
             * @example null
             */
            importJobId?: Record<string, never>;
            /**
             * @description Financial Year (year in which FY ends)
             * @example 2026
             */
            financialYear: number;
            /**
             * @description Quarter (Q1=Jul-Sep, Q2=Oct-Dec, Q3=Jan-Mar, Q4=Apr-Jun)
             * @example Q1
             * @enum {string}
             */
            quarter: "Q1" | "Q2" | "Q3" | "Q4";
            /**
             * @description Human-readable FY label
             * @example FY2026
             */
            fyLabel: string;
            /**
             * @description Human-readable quarter label
             * @example Q1 FY2026
             */
            quarterLabel: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-08-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2025-08-15T10:30:00Z
             */
            updatedAt: string;
            /** @description Provider details */
            provider?: Record<string, never>;
            /** @description Category details */
            category?: Record<string, never>;
        };
        UpdateExpenseDto: Record<string, never>;
        CreateImportJobDto: {
            /**
             * @description Original filename of the CSV being imported
             * @example commbank-transactions-2025-01.csv
             */
            filename: string;
            /**
             * @description Bank or source of the CSV file
             * @default manual
             * @enum {string}
             */
            source: "commbank" | "nab" | "westpac" | "anz" | "manual" | "other";
        };
        ImportJob: Record<string, never>;
        UpdateImportJobDto: {
            /**
             * @description Original filename of the CSV being imported
             * @example commbank-transactions-2025-01.csv
             */
            filename?: string;
            /**
             * @description Bank or source of the CSV file
             * @enum {string}
             */
            source?: "commbank" | "nab" | "westpac" | "anz" | "manual" | "other";
            /**
             * @description Current status of the import job
             * @enum {string}
             */
            status?: "pending" | "completed" | "rolled_back" | "failed";
            /** @description Total number of rows in the CSV file */
            totalRows?: number;
            /** @description Number of expenses successfully imported */
            importedCount?: number;
            /** @description Number of rows skipped */
            skippedCount?: number;
            /** @description Number of rows that failed */
            errorCount?: number;
            /** @description Error message if import failed */
            errorMessage?: string;
        };
        CreateIncomeDto: {
            /**
             * @description Invoice date (YYYY-MM-DD)
             * @example 2024-01-15
             */
            date: string;
            /**
             * @description Client UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientId: string;
            /**
             * @description Invoice number
             * @example INV-2024-001
             */
            invoiceNum?: string;
            /**
             * @description Work description (encrypted at rest)
             * @example Website development
             */
            description?: string;
            /**
             * @description Subtotal in cents (ex-GST)
             * @example 100000
             */
            subtotalCents: number;
            /**
             * @description GST collected in cents
             * @example 10000
             */
            gstCents: number;
            /**
             * @description Payment received
             * @default false
             */
            isPaid: boolean;
        };
        Income: Record<string, never>;
        UpdateIncomeDto: Record<string, never>;
        CreateProviderDto: {
            /**
             * @description Provider name
             * @example GitHub
             */
            name: string;
            /**
             * @description International provider (GST-free)
             * @default false
             * @example true
             */
            isInternational: boolean;
            /**
             * @description Default category UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            defaultCategoryId?: string;
            /**
             * @description ABN (11 digits) or ARN (9 digits)
             * @example 51824753556
             */
            abnArn?: string;
        };
        Provider: Record<string, never>;
        UpdateProviderDto: Record<string, never>;
        CreateRecurringExpenseDto: {
            /**
             * @description Name for this recurring expense
             * @example iinet Internet
             */
            name: string;
            /**
             * @description Description template for generated expenses
             * @example Monthly internet service
             */
            description?: string;
            /**
             * @description Amount in cents (inc GST)
             * @example 8999
             */
            amountCents: number;
            /**
             * @description GST in cents (auto-calculated if not provided)
             * @example 818
             */
            gstCents?: number;
            /**
             * @description Business use percentage (0-100)
             * @default 100
             * @example 100
             */
            bizPercent: number;
            /**
             * @description Currency code (ISO 4217)
             * @default AUD
             * @example AUD
             */
            currency: string;
            /**
             * @description Schedule frequency
             * @example monthly
             * @enum {string}
             */
            schedule: "monthly" | "quarterly" | "yearly";
            /**
             * @description Day of month (1-28)
             * @default 1
             * @example 1
             */
            dayOfMonth: number;
            /**
             * @description Start date (YYYY-MM-DD)
             * @example 2025-07-01
             */
            startDate: string;
            /**
             * @description End date (YYYY-MM-DD)
             * @example 2026-06-30
             */
            endDate?: string;
            /**
             * @description Whether template is active
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Provider UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            providerId: string;
            /**
             * @description Category UUID
             * @example 123e4567-e89b-12d3-a456-426614174001
             */
            categoryId: string;
        };
        RecurringExpenseResponseDto: {
            /** @description Recurring expense UUID */
            id: string;
            /** @description Name of recurring expense */
            name: string;
            /** @description Description template */
            description?: Record<string, never>;
            /** @description Amount in cents */
            amountCents: number;
            /** @description GST in cents */
            gstCents: number;
            /** @description Business use percentage */
            bizPercent: number;
            /** @description Currency code */
            currency: string;
            /**
             * @description Schedule frequency
             * @enum {string}
             */
            schedule: "monthly" | "quarterly" | "yearly";
            /** @description Day of month (1-28) */
            dayOfMonth: number;
            /** @description Start date */
            startDate: string;
            /** @description End date */
            endDate?: Record<string, never>;
            /** @description Whether template is active */
            isActive: boolean;
            /** @description Date of last generated expense */
            lastGeneratedDate?: Record<string, never>;
            /** @description Next due date */
            nextDueDate: string;
            /** @description Provider ID */
            providerId: string;
            /** @description Provider name */
            providerName?: string;
            /** @description Category ID */
            categoryId: string;
            /** @description Category name */
            categoryName?: string;
            /**
             * Format: date-time
             * @description Created timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Updated timestamp
             */
            updatedAt: string;
        };
        GenerateExpensesResultDto: {
            /** @description Number of expenses generated */
            generated: number;
            /** @description Number of templates skipped (already generated) */
            skipped: number;
            /** @description List of generated expense IDs */
            expenseIds: string[];
            /** @description Details of each generated expense */
            details: unknown[];
        };
        UpdateRecurringExpenseDto: {
            /**
             * @description Name for this recurring expense
             * @example iinet Internet
             */
            name?: string;
            /**
             * @description Description template for generated expenses
             * @example Monthly internet service
             */
            description?: string;
            /**
             * @description Amount in cents (inc GST)
             * @example 8999
             */
            amountCents?: number;
            /**
             * @description GST in cents (auto-calculated if not provided)
             * @example 818
             */
            gstCents?: number;
            /**
             * @description Business use percentage (0-100)
             * @default 100
             * @example 100
             */
            bizPercent: number;
            /**
             * @description Currency code (ISO 4217)
             * @default AUD
             * @example AUD
             */
            currency: string;
            /**
             * @description Schedule frequency
             * @example monthly
             * @enum {string}
             */
            schedule?: "monthly" | "quarterly" | "yearly";
            /**
             * @description Day of month (1-28)
             * @default 1
             * @example 1
             */
            dayOfMonth: number;
            /**
             * @description Start date (YYYY-MM-DD)
             * @example 2025-07-01
             */
            startDate?: string;
            /**
             * @description End date (YYYY-MM-DD)
             * @example 2026-06-30
             */
            endDate?: string;
            /**
             * @description Whether template is active
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Provider UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            providerId?: string;
            /**
             * @description Category UUID
             * @example 123e4567-e89b-12d3-a456-426614174001
             */
            categoryId?: string;
        };
        FYIncomeSummaryDto: {
            /**
             * @description Total income in cents (inc GST)
             * @example 5500000
             */
            totalIncomeCents: number;
            /**
             * @description Total paid income in cents
             * @example 5000000
             */
            paidIncomeCents: number;
            /**
             * @description Total unpaid income in cents
             * @example 500000
             */
            unpaidIncomeCents: number;
            /**
             * @description GST collected in cents
             * @example 500000
             */
            gstCollectedCents: number;
            /**
             * @description Number of invoices
             * @example 45
             */
            count: number;
        };
        CategoryExpenseDto: {
            /**
             * @description Category ID
             * @example 1
             */
            categoryId: number;
            /**
             * @description Category name
             * @example Software
             */
            name: string;
            /**
             * @description BAS label
             * @example 1B
             */
            basLabel: string;
            /**
             * @description Total expenses in cents
             * @example 500000
             */
            totalCents: number;
            /**
             * @description GST paid in cents (claimable)
             * @example 45454
             */
            gstCents: number;
            /**
             * @description Number of expenses
             * @example 24
             */
            count: number;
        };
        FYExpenseSummaryDto: {
            /**
             * @description Total expenses in cents
             * @example 2200000
             */
            totalExpensesCents: number;
            /**
             * @description Total claimable GST in cents
             * @example 200000
             */
            gstPaidCents: number;
            /**
             * @description Number of expenses
             * @example 156
             */
            count: number;
            /** @description Expenses by category */
            byCategory: components["schemas"]["CategoryExpenseDto"][];
        };
        FYSummaryDto: {
            /**
             * @description Financial year
             * @example 2026
             */
            financialYear: number;
            /**
             * @description FY label
             * @example FY2026
             */
            fyLabel: string;
            /**
             * @description Period start date
             * @example 2025-07-01
             */
            periodStart: string;
            /**
             * @description Period end date
             * @example 2026-06-30
             */
            periodEnd: string;
            /** @description Income summary */
            income: components["schemas"]["FYIncomeSummaryDto"];
            /** @description Expense summary */
            expenses: components["schemas"]["FYExpenseSummaryDto"];
            /**
             * @description Net profit in cents
             * @example 3300000
             */
            netProfitCents: number;
            /**
             * @description Net GST payable in cents
             * @example 300000
             */
            netGstPayableCents: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok" | "error";
                        /** @enum {string} */
                        database?: "connected" | "disconnected";
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    BasController_getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quarter (Q1, Q2, Q3, Q4) */
                quarter: string;
                /** @description Financial year (e.g., 2025 for FY2024-25) */
                year: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description BAS summary for the quarter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasSummaryDto"];
                };
            };
            /** @description Invalid quarter format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BasController_getQuarters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Financial year */
                year: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of quarter date ranges */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Q1 */
                        quarter?: string;
                        /** @example 2024-07-01 */
                        start?: string;
                        /** @example 2024-09-30 */
                        end?: string;
                    }[];
                };
            };
        };
    };
    CategoriesController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by BAS label (e.g., 1B) */
                basLabel?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Category created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    CategoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Category updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by PSI eligibility (true/false) */
                psiEligible?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    ClientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientDto"];
            };
        };
        responses: {
            /** @description Client created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
        };
    };
    ClientsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientDto"];
            };
        };
        responses: {
            /** @description Client updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CsvImportController_importFromFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description CSV file to import
                     */
                    file: string;
                    /**
                     * @description Predefined source format
                     * @enum {string}
                     */
                    source?: "custom" | "commbank" | "amex" | "nab" | "westpac" | "anz";
                    /**
                     * @description Provider matching threshold
                     * @default 0.6
                     */
                    matchThreshold?: number;
                    /**
                     * @description Skip duplicate expenses
                     * @default true
                     */
                    skipDuplicates?: boolean;
                    /**
                     * @description Preview mode - do not create expenses
                     * @default false
                     */
                    dryRun?: boolean;
                };
            };
        };
        responses: {
            /** @description Import completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvImportResponseDto"];
                };
            };
            /** @description Invalid CSV format or missing required columns */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CsvImportController_importFromContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description CSV content as string
                     * @example Date,Item,Total,GST
                     *     2025-07-15,Internet,$88.00,$8.00
                     */
                    content: string;
                    /** @enum {string} */
                    source?: "custom" | "commbank" | "amex";
                    matchThreshold?: number;
                    skipDuplicates?: boolean;
                    dryRun?: boolean;
                };
            };
        };
        responses: {
            /** @description Import completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvImportResponseDto"];
                };
            };
        };
    };
    CsvImportController_previewImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CsvImportRequestDto"];
            };
        };
        responses: {
            /** @description Preview results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvImportResponseDto"];
                };
            };
        };
    };
    CsvImportController_importIncomesFromFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description CSV file to import
                     */
                    file: string;
                    /**
                     * @description Predefined source format
                     * @enum {string}
                     */
                    source?: "custom";
                    /**
                     * @description Client matching threshold
                     * @default 0.6
                     */
                    matchThreshold?: number;
                    /**
                     * @description Skip duplicate incomes
                     * @default true
                     */
                    skipDuplicates?: boolean;
                    /**
                     * @description Preview mode - do not create incomes
                     * @default false
                     */
                    dryRun?: boolean;
                    /**
                     * @description Mark all imported incomes as paid
                     * @default false
                     */
                    markAsPaid?: boolean;
                };
            };
        };
        responses: {
            /** @description Import completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeCsvImportResponseDto"];
                };
            };
            /** @description Invalid CSV format or missing required columns */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CsvImportController_importIncomesFromContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description CSV content as string
                     * @example Client,Invoice #,Subtotal,GST,Total
                     *     Acme Corp,INV-001,$1000,$100,$1100
                     */
                    content: string;
                    /** @enum {string} */
                    source?: "custom";
                    matchThreshold?: number;
                    skipDuplicates?: boolean;
                    dryRun?: boolean;
                    markAsPaid?: boolean;
                };
            };
        };
        responses: {
            /** @description Import completed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeCsvImportResponseDto"];
                };
            };
        };
    };
    CsvImportController_previewIncomeImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["IncomeCsvImportRequestDto"];
            };
        };
        responses: {
            /** @description Preview results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeCsvImportResponseDto"];
                };
            };
        };
    };
    ExpensesController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by category UUID */
                categoryId?: string;
                /** @description Filter by provider UUID */
                providerId?: string;
                /** @description Start date (YYYY-MM-DD) */
                startDate?: string;
                /** @description End date (YYYY-MM-DD) */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of expenses with FY/Quarter info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponseDto"][];
                };
            };
        };
    };
    ExpensesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseDto"];
            };
        };
        responses: {
            /** @description Expense created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponseDto"];
                };
            };
        };
    };
    ExpensesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The expense with FY/Quarter info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponseDto"];
                };
            };
            /** @description Expense not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expense deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expense not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseDto"];
            };
        };
        responses: {
            /** @description Expense updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponseDto"];
                };
            };
            /** @description Expense not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of import jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportJobDto"];
            };
        };
        responses: {
            /** @description Import job created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Import job UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The import job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            /** @description Import job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Import job UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import job deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Import job has associated expenses */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Import job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Import job UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateImportJobDto"];
            };
        };
        responses: {
            /** @description Import job updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            /** @description Import job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_findOneWithExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Import job UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import job with expenses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Import job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Import job UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import job statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImportJobsController_rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Import job UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollback successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Import job already rolled back */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Import job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IncomesController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by client UUID */
                clientId?: string;
                /** @description Filter by payment status (true/false) */
                isPaid?: string;
                /** @description Start date (YYYY-MM-DD) */
                startDate?: string;
                /** @description End date (YYYY-MM-DD) */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of incomes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Income"][];
                };
            };
        };
    };
    IncomesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncomeDto"];
            };
        };
        responses: {
            /** @description Income created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Income"];
                };
            };
        };
    };
    IncomesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Income UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The income */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Income"];
                };
            };
            /** @description Income not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IncomesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Income UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Income deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Income not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IncomesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Income UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIncomeDto"];
            };
        };
        responses: {
            /** @description Income updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Income"];
                };
            };
            /** @description Income not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IncomesController_markAsPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Income UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Income marked as paid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Income"];
                };
            };
            /** @description Income not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IncomesController_markAsUnpaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Income UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Income marked as unpaid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Income"];
                };
            };
            /** @description Income not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProvidersController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by international status (true/false) */
                international?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    ProvidersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderDto"];
            };
        };
        responses: {
            /** @description Provider created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    ProvidersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Provider not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProvidersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provider not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProvidersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderDto"];
            };
        };
        responses: {
            /** @description Provider updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Provider not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringExpensesController_findAll: {
        parameters: {
            query?: {
                /** @description Filter to only active templates */
                activeOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recurring expense templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpenseResponseDto"][];
                };
            };
        };
    };
    RecurringExpensesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringExpenseDto"];
            };
        };
        responses: {
            /** @description Template created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpenseResponseDto"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provider or category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringExpensesController_findDue: {
        parameters: {
            query?: {
                /** @description Check due as of this date (YYYY-MM-DD) */
                asOfDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of due recurring expense templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpenseResponseDto"][];
                };
            };
        };
    };
    RecurringExpensesController_generate: {
        parameters: {
            query?: {
                /** @description Generate expenses up to this date (YYYY-MM-DD) */
                asOfDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expenses generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateExpensesResultDto"];
                };
            };
        };
    };
    RecurringExpensesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recurring expense UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recurring expense template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpenseResponseDto"];
                };
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringExpensesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recurring expense UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecurringExpensesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recurring expense UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringExpenseDto"];
            };
        };
        responses: {
            /** @description Template updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpenseResponseDto"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getFYSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Financial year (e.g., 2026 for July 2025 - June 2026) */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FY summary returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FYSummaryDto"];
                };
            };
            /** @description Invalid financial year */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getFYSummaryPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Financial year (e.g., 2026 for July 2025 - June 2026) */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Invalid financial year */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_getBasSummaryPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quarter (Q1, Q2, Q3, Q4) */
                quarter: string;
                /** @description Financial year (e.g., 2026 for FY2025-26) */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Invalid quarter or year */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
